// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR96KSJMkfdW-8Z7YgTa-zPZJx1ogcFV0',
    appId: '1:840652510106:web:d1decdbf85e5d60676a023',
    messagingSenderId: '840652510106',
    projectId: 'caloriebase-4d508',
    authDomain: 'caloriebase-4d508.firebaseapp.com',
    storageBucket: 'caloriebase-4d508.firebasestorage.app',
    measurementId: 'G-KLJ8P9Z9E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBijO5eiZl0Kby1R8DKCTHXWZXut1uqR3s',
    appId: '1:840652510106:android:1d32999b7f885f9b76a023',
    messagingSenderId: '840652510106',
    projectId: 'caloriebase-4d508',
    storageBucket: 'caloriebase-4d508.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCo8sQPzSfWX3W45axRf2A5Jbil9Ynmy8',
    appId: '1:840652510106:ios:e5cc6ec59e125cd376a023',
    messagingSenderId: '840652510106',
    projectId: 'caloriebase-4d508',
    storageBucket: 'caloriebase-4d508.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCo8sQPzSfWX3W45axRf2A5Jbil9Ynmy8',
    appId: '1:840652510106:ios:e5cc6ec59e125cd376a023',
    messagingSenderId: '840652510106',
    projectId: 'caloriebase-4d508',
    storageBucket: 'caloriebase-4d508.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR96KSJMkfdW-8Z7YgTa-zPZJx1ogcFV0',
    appId: '1:840652510106:web:77f30315e9ad7b0d76a023',
    messagingSenderId: '840652510106',
    projectId: 'caloriebase-4d508',
    authDomain: 'caloriebase-4d508.firebaseapp.com',
    storageBucket: 'caloriebase-4d508.firebasestorage.app',
    measurementId: 'G-WPS0LNC9EV',
  );
}
